CREATE TABLE USUARIO
(
    ID      UUID PRIMARY KEY      DEFAULT GEN_RANDOM_UUID(),
    VERSION INTEGER      NOT NULL DEFAULT 0,
    NOME    VARCHAR(100) NOT NULL,
    EMAIL   VARCHAR(150) NOT NULL UNIQUE,
    SENHA   VARCHAR(255) NOT NULL,
    ROLE    VARCHAR(1)   NOT NULL
        CHECK (ROLE IN ('A', 'M'))
);