CREATE TABLE PROJETO
(
    ID        UUID PRIMARY KEY      DEFAULT GEN_RANDOM_UUID(),
    VERSION   INTEGER      NOT NULL DEFAULT 0,
    NOME      VARCHAR(100) NOT NULL UNIQUE,
    DESCRICAO VARCHAR(500) NOT NULL,
    DONO_FK   UUID         NOT NULL,
    CONSTRAINT FK_PROJETO_DONO_USUARIO FOREIGN KEY (DONO_FK) REFERENCES USUARIO (ID)
);

CREATE TABLE PROJETO_MEMBROS
(
    PROJETO_FK UUID NOT NULL,
    MEMBRO_FK  UUID NOT NULL,
    CONSTRAINT PK_MEMBROS PRIMARY KEY (PROJETO_FK, MEMBRO_FK),

    CONSTRAINT FK_MEMBROS_PROJETO
        FOREIGN KEY (PROJETO_FK)
            REFERENCES PROJETO (ID),

    CONSTRAINT FK_MEMBROS_USUARIO
        FOREIGN KEY (MEMBRO_FK)
            REFERENCES USUARIO (ID)
);
