CREATE TABLE TAREFA
(
    ID                 UUID PRIMARY KEY       DEFAULT GEN_RANDOM_UUID(),
    VERSION            INTEGER       NOT NULL DEFAULT 0,
    TITULO             VARCHAR(300)  NOT NULL,
    CODIGO             VARCHAR(10)   NOT NULL UNIQUE,
    DESCRICAO          VARCHAR(1000) NOT NULL,
    STATUS             VARCHAR(1)    NOT NULL,
    PRIORIDADE         VARCHAR(1)    NOT NULL,
    RESPONSAVEL_FK     UUID          NOT NULL,
    PROJETO_FK         UUID          NOT NULL,
    DATA_CRIACAO       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ULTIMA_ATUALIZACAO TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (STATUS IN ('T', 'P', 'D')),
    CHECK (PRIORIDADE IN ('L', 'M', 'H', 'C')),
    CONSTRAINT FK_TAREFA_RESPONSAVEL FOREIGN KEY (RESPONSAVEL_FK) REFERENCES USUARIO (ID),
    CONSTRAINT FK_TAREFA_PROJETO FOREIGN KEY (PROJETO_FK) REFERENCES PROJETO (ID)
);
