export enum ProblemaCode {
  ERRO_INTERNO = "ERRO_INTERNO",
  NAO_ENCONTRADO = "NAO_ENCONTRADO",
  TOKEN_INVALIDO = "TOKEN_INVALIDO",
  DUPLICIDADE = "DUPLICIDADE",
  RESPONSAVEL_NAO_PERTENCE_AO_PROJETO = "RESPONSAVEL_NAO_PERTENCE_AO_PROJETO",
  MOVER_TAREFA = "MOVER_TAREFA",
  FECHAR_TAREFA = "FECHAR_TAREFA",
  ATINGIU_LIMITE_TAREFAS = "ATINGIU_LIMITE_TAREFAS",
  DONO_NAO_POSSUI_ROLE_ADMIN = "DONO_NAO_POSSUI_ROLE_ADMIN",
}
