spring.application.name=cancan
spring.datasource.url=jdbc:postgresql://localhost:5432/cancan
spring.datasource.username=admin
spring.datasource.password=1324


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

security.jwt.secret=uma-chave-bem-grande-com-32-caracteres-ou-mais
security.jwt.expiration=3600